/**
 * RuDiK 1.0 Async APIs
 * Collection of APIs for inducing declarative rules with RuDiK and few others utility methods for RDF knowledge graphs accesible via a SPARQL endpoint.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: stefano.ortona@meltwater.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package asu.edu.rule_miner.api.model;

import java.util.Objects;
import asu.edu.rule_miner.api.model.EntityPair;
import asu.edu.rule_miner.api.model.HornRuleBody;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * HornRule
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-24T18:17:08.173Z")
public class HornRule   {
  @JsonProperty("body")
  private HornRuleBody body = null;

  @JsonProperty("generationCoverage")
  private List<EntityPair> generationCoverage = new ArrayList<EntityPair>();

  @JsonProperty("validationCoverage")
  private List<EntityPair> validationCoverage = new ArrayList<EntityPair>();

  @JsonProperty("score")
  private Double score = null;

  public HornRule body(HornRuleBody body) {
    this.body = body;
    return this;
  }

   /**
   * Get body
   * @return body
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public HornRuleBody getBody() {
    return body;
  }

  public void setBody(HornRuleBody body) {
    this.body = body;
  }

  public HornRule generationCoverage(List<EntityPair> generationCoverage) {
    this.generationCoverage = generationCoverage;
    return this;
  }

  public HornRule addGenerationCoverageItem(EntityPair generationCoverageItem) {
    this.generationCoverage.add(generationCoverageItem);
    return this;
  }

   /**
   * Generation examples covered by the rule.
   * @return generationCoverage
  **/
  @ApiModelProperty(example = "null", value = "Generation examples covered by the rule.")
  public List<EntityPair> getGenerationCoverage() {
    return generationCoverage;
  }

  public void setGenerationCoverage(List<EntityPair> generationCoverage) {
    this.generationCoverage = generationCoverage;
  }

  public HornRule validationCoverage(List<EntityPair> validationCoverage) {
    this.validationCoverage = validationCoverage;
    return this;
  }

  public HornRule addValidationCoverageItem(EntityPair validationCoverageItem) {
    this.validationCoverage.add(validationCoverageItem);
    return this;
  }

   /**
   * Validation examples covered by the rule.
   * @return validationCoverage
  **/
  @ApiModelProperty(example = "null", value = "Validation examples covered by the rule.")
  public List<EntityPair> getValidationCoverage() {
    return validationCoverage;
  }

  public void setValidationCoverage(List<EntityPair> validationCoverage) {
    this.validationCoverage = validationCoverage;
  }

  public HornRule score(Double score) {
    this.score = score;
    return this;
  }

   /**
   * Confidence score given to output rules.
   * @return score
  **/
  @ApiModelProperty(example = "null", value = "Confidence score given to output rules.")
  public Double getScore() {
    return score;
  }

  public void setScore(Double score) {
    this.score = score;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HornRule hornRule = (HornRule) o;
    return Objects.equals(this.body, hornRule.body) &&
        Objects.equals(this.generationCoverage, hornRule.generationCoverage) &&
        Objects.equals(this.validationCoverage, hornRule.validationCoverage) &&
        Objects.equals(this.score, hornRule.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(body, generationCoverage, validationCoverage, score);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HornRule {\n");
    
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    generationCoverage: ").append(toIndentedString(generationCoverage)).append("\n");
    sb.append("    validationCoverage: ").append(toIndentedString(validationCoverage)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

