/**
 * RuDiK 1.0 Async APIs
 * Collection of APIs for inducing declarative rules with RuDiK and few others utility methods for RDF knowledge graphs accesible via a SPARQL endpoint.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: stefano.ortona@meltwater.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package asu.edu.rule_miner.api.model;

import java.util.Objects;
import asu.edu.rule_miner.api.model.RuleResult;
import asu.edu.rule_miner.api.model.VariableBinding;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * RuleInstantiation
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-24T18:17:08.173Z")
public class RuleInstantiation   {
  @JsonProperty("specification")
  private RuleResult specification = null;

  @JsonProperty("instance")
  private List<VariableBinding> instance = new ArrayList<VariableBinding>();

  public RuleInstantiation specification(RuleResult specification) {
    this.specification = specification;
    return this;
  }

   /**
   * Get specification
   * @return specification
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public RuleResult getSpecification() {
    return specification;
  }

  public void setSpecification(RuleResult specification) {
    this.specification = specification;
  }

  public RuleInstantiation instance(List<VariableBinding> instance) {
    this.instance = instance;
    return this;
  }

  public RuleInstantiation addInstanceItem(VariableBinding instanceItem) {
    this.instance.add(instanceItem);
    return this;
  }

   /**
   * A single instantation of the given input rule, where an array of variable bindigns assign to each varable in the rule an actual entity of the graph.
   * @return instance
  **/
  @ApiModelProperty(example = "null", required = true, value = "A single instantation of the given input rule, where an array of variable bindigns assign to each varable in the rule an actual entity of the graph.")
  public List<VariableBinding> getInstance() {
    return instance;
  }

  public void setInstance(List<VariableBinding> instance) {
    this.instance = instance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuleInstantiation ruleInstantiation = (RuleInstantiation) o;
    return Objects.equals(this.specification, ruleInstantiation.specification) &&
        Objects.equals(this.instance, ruleInstantiation.instance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(specification, instance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuleInstantiation {\n");
    
    sb.append("    specification: ").append(toIndentedString(specification)).append("\n");
    sb.append("    instance: ").append(toIndentedString(instance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

