/**
 * RuDiK 1.0 Async APIs
 * Collection of APIs for inducing declarative rules with RuDiK and few others utility methods for RDF knowledge graphs accesible via a SPARQL endpoint.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: stefano.ortona@meltwater.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package asu.edu.rule_miner.api.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * RuleResult
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-24T18:17:08.173Z")
public class RuleResult {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("timeComputed")
  private Date timeComputed = null;

  @JsonProperty("specification")
  private RuleSpecification specification = null;

  @JsonProperty("statistics")
  private RuleStatistics statistics = null;

  @JsonProperty("rule")
  private List<HornRule> rule = new ArrayList<HornRule>();

  @JsonProperty("metadata")
  private List<KeyValuePair> metadata = new ArrayList<KeyValuePair>();

  public RuleResult id(String id) {
    this.id = id;
    return this;
  }

  /**
   * ID of the rule result. Currently same one used for the RuleSpecification+TimeStamp of retrieval.
   * @return id
   **/
  @ApiModelProperty(example = "null", required = true, value = "ID of the rule result. Currently same one used for the RuleSpecification+TimeStamp of retrieval.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RuleResult timeComputed(Date timeComputed) {
    this.timeComputed = timeComputed;
    return this;
  }

  /**
   * ID of the rule result. Currently same one used for the RuleSpecification+TimeStamp of retrieval.
   * @return id
   **/
  @ApiModelProperty(required = true, value = "Time stamp of when this rule result was computed.")
  public Date getTimeComputed() {
    return this.timeComputed;
  }

  public void setTimeComputed(Date time) {
    this.timeComputed = time;
  }

  public RuleResult specification(RuleSpecification specification) {
    this.specification = specification;
    return this;
  }

  /**
   * Get specification
   * @return specification
   **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public RuleSpecification getSpecification() {
    return specification;
  }

  public void setSpecification(RuleSpecification specification) {
    this.specification = specification;
  }

  public RuleResult statistics(RuleStatistics statistics) {
    this.statistics = statistics;
    return this;
  }

  /**
   * Get statistics
   * @return statistics
   **/
  @ApiModelProperty(example = "null", value = "")
  public RuleStatistics getStatistics() {
    return statistics;
  }

  public void setStatistics(RuleStatistics statistics) {
    this.statistics = statistics;
  }

  public RuleResult rule(List<HornRule> rule) {
    this.rule = rule;
    return this;
  }

  public RuleResult addRuleItem(HornRule ruleItem) {
    this.rule.add(ruleItem);
    return this;
  }

  /**
   * Output logical body rules produced by RuDiK including their statistics.
   * @return rule
   **/
  @ApiModelProperty(example = "null", required = true, value = "Output logical body rules produced by RuDiK including their statistics.")
  public List<HornRule> getRule() {
    return rule;
  }

  public void setRule(List<HornRule> rule) {
    this.rule = rule;
  }

  public RuleResult metadata(List<KeyValuePair> metadata) {
    this.metadata = metadata;
    return this;
  }

  public RuleResult addMetadataItem(KeyValuePair metadataItem) {
    this.metadata.add(metadataItem);
    return this;
  }

  /**
   * Metadata includes things like the time of creation, the version of the induction system, …
   * @return metadata
   **/
  @ApiModelProperty(example = "null", value = "Metadata includes things like the time of creation, the version of the induction system, …")
  public List<KeyValuePair> getMetadata() {
    return metadata;
  }

  public void setMetadata(List<KeyValuePair> metadata) {
    this.metadata = metadata;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if ((o == null) || (getClass() != o.getClass())) {
      return false;
    }
    final RuleResult ruleResult = (RuleResult) o;
    return Objects.equals(this.id, ruleResult.id) && Objects.equals(this.specification, ruleResult.specification)
        && Objects.equals(this.statistics, ruleResult.statistics) && Objects.equals(this.rule, ruleResult.rule)
        && Objects.equals(this.metadata, ruleResult.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, specification, statistics, rule, metadata);
  }

  @Override
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class RuleResult {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    specification: ").append(toIndentedString(specification)).append("\n");
    sb.append("    statistics: ").append(toIndentedString(statistics)).append("\n");
    sb.append("    rule: ").append(toIndentedString(rule)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
